name: Build wheels for MacOS
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build-wheels-for-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        python_version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Install dependencies using brew
        id: install-using-brew
        run: |
          brew install llvm
          brew install gcc@12
          brew install libomp # for openmp support
          brew install boost
          brew install armadillo
          brew install libtorch
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build atomsciml
        run: |
          export LDFLAGS=-L$(brew --cellar gcc@11)/$(brew list --versions gcc@12 | tr ' ' '\n' | tail -n 1)/lib/gcc/12
          python -m pip install scikit-build cython pybind11[global]
          python setup.py build bdist_wheel -j 4
        # env:
          # passing cmake arguments to scikit-build when dealing with cmake, using either SKBUILD_CONFIGURE_OPTIONS or CMAKE_ARGS env
          # SKBUILD_CONFIGURE_OPTIONS: "-DOPENSSL_ROOT_DIR=${{steps.install-using-brew.outputs.openssl_3_prefix}}"
          # CMAKE_ARGS: "-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3"
          # the default clang/clang++ in macos doen't support -fopenmp
          # we installed llvm using brew before, and set to use them here
          # to support openmp
          # CC: "/usr/local/opt/llvm/bin/clang" 
          # CXX: "/usr/local/opt/llvm/bin/clang++"
      - uses: actions/upload-artifact@v2
        with:
          name: macos-wheels
          path: dist/*.whl
