name: Build wheels for Linux
on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]
jobs:
  build-wheels-for-linux:
    strategy:
      matrix:
        manylinux: ["manylinux2014_x86_64", "manylinux_2_24_x86_64"]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: build wheels using manylinux docker images
        run: |
          if [[ "${{ matrix.manylinux }}" == "manylinux_2_24_x86_64" ]]
          then
            docker pull "quay.io/pypa/manylinux_2_24_x86_64":latest
            docker container run -i --rm \
              -v "$(pwd)":/root/atomsciml \
              "quay.io/pypa/manylinux_2_24_x86_64":latest bash /root/atomsciml/build_wheels/build_wheels_manylinux_2_24_x86_64.sh -p 4 -m false
          elif [[ "${{ matrix.manylinux }}" == "manylinux2014_x86_64" ]]
          then
            docker pull "quay.io/pypa/manylinux2014_x86_64":latest
            docker container run -i --rm \
              -v "$(pwd)":/root/atomsciml \
              "quay.io/pypa/manylinux2014_x86_64":latest bash /root/atomsciml/build_wheels/build_wheels_manylinux2014_x86_64.sh -p 4
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: linux-wheels
          path: dist/*manylinux*.whl